<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_MicrosoftClarity
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/** @var $block \Dss\MicrosoftClarity\Block\Script */
/** @var $escaper \Magento\Framework\Escaper */
if ($block->isEnabled()):
    $clarityCode = $block->getClarityTrackingCode();
    $isCustomerGroupTagEnabled = $block->isCustomerGroupTagEnabled();
    $customerGroup = $block->getCustomerGroup();
    ?>
    <script type="text/x-magento-init">
        {
          "*": {
              "Dss_MicrosoftClarity/js/clarity": {
                  "clarityCode": "<?= $escaper->escapeHtml($clarityCode) ?>",
                  "isCustomerGroupTagEnabled": <?= $isCustomerGroupTagEnabled ? 'true' : 'false' ?>,
                  "customerGroup": "<?= $escaper->escapeJs($customerGroup) ?>"
              }
          }
        }
    </script>
<!-- END MICROSOFT CLARITY TRACKING CODE -->
<?php endif; ?>